import type { Metadata } from "next";

import "./globals.css";
import { CartProvider } from "@modules/cart/context";
import { UserProvider } from "@modules/user/context";
import { ToastProvider } from "@modules/app/modules/toast/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <UserProvider>
            <CartProvider>{children}</CartProvider>
          </UserProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
